**Примеры из раздела 2.2**

*Кортеж (Tuple)* - структура данных (контейнер) в виде неизменяемой индексируемой
последовательности элементов какого-либо типа (элементы индексируются с единицы).
Синтаксис определения кортежа: ```(element1, element2, ...)```

Примеры кортежей:

In [1]:
# пустой кортеж:
()

()

In [2]:
# кортеж из элементов типа String:
favoritelang = ("Python","Julia","R")

("Python", "Julia", "R")

In [3]:
# кортеж из целых чисел:
x1 = (1, 2, 3)

(1, 2, 3)

In [4]:
# кортеж из элементов разных типов:
x2 = (1, 2.0, "tmp")

(1, 2.0, "tmp")

In [5]:
# именованный кортеж:
x3 = (a=2, b=1+2)

(a = 2, b = 3)

Примеры операций над кортежами:

In [6]:
# длина кортежа x2:
length(x2)

3

In [7]:
# обратиться к элементам кортежа x2:
x2[1], x2[2], x2[3]

(1, 2.0, "tmp")

In [8]:
# произвести какую-либо операцию (сложение)
# с вторым и третьим элементами кортежа x1:
с = x1[2] + x1[3]

5

In [9]:
# обращение к элементам именованного кортежа x3:
x3.a, x3.b, x3[2]

(2, 3, 3)

In [10]:
# проверка вхождения элементов tmp и 0 в кортеж x2
# (два способа обращения к методу in()):
in("tmp", x2), 0 in x2

(true, false)

*Словарь* - неупорядоченный набор связанных между собой по ключу данных.
Синтаксис определения словаря: ```Dict(key1 => value1, key2 => value2, ...)```

Примеры словарей и операций над ними:

In [13]:
# создать словарь с именем phonebook:
phonebook = Dict("Иванов И.И." => ("867-5309","333-5544"), "Бухгалтерия" => "555-2368")

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [14]:
# вывести ключи словаря:
keys(phonebook)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "Бухгалтерия"
  "Иванов И.И."

In [15]:
# вывести значения элементов словаря:
values(phonebook)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  "555-2368"
  ("867-5309", "333-5544")

In [16]:
# вывести заданные в словаре пары "ключ - значение":
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [17]:
# проверка вхождения ключа в словарь:
haskey(phonebook, "Иванов И.И.")

true

In [18]:
# добавить элемент в словарь:
phonebook["Сидоров П.С."] = "555-3344"

"555-3344"

In [19]:
pairs(phonebook)

Dict{String, Any} with 3 entries:
  "Сидоров П.С." => "555-3344"
  "Бухгалтерия"  => "555-2368"
  "Иванов И.И."  => ("867-5309", "333-5544")

In [20]:
# удалить ключ и связанные с ним значения из словаря:
pop!(phonebook, "Иванов И.И.")

("867-5309", "333-5544")

In [21]:
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Сидоров П.С." => "555-3344"
  "Бухгалтерия"  => "555-2368"

In [22]:
# Объединение словарей (функция merge()):
a = Dict("foo" => 0.0, "bar" => 42.0);
b = Dict("baz" => 17, "bar" => 13.0);
merge(a, b), merge(b,a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

*Множество*, как структура данных в Julia, соответствует множеству, как математическому объекту, то есть является неупорядоченной совокупностью элементов какого-либо
типа. Возможные операции над множествами: объединение, пересечение, разность;
принадлежность элемента множеству.
Синтаксис определения множества: ```Set([itr])```, где ```itr``` - набор значений, сгенерированных данным итерируемым объектом или пустое
множество.

Примеры множеств и операций над ними:

In [23]:
# создать множество из четырёх целочисленных значений:
A = Set([1, 3, 4, 5])

Set{Int64} with 4 elements:
  5
  4
  3
  1

In [24]:
# создать множество из 11 символьных значений:
B = Set("abrakadabra")

Set{Char} with 5 elements:
  'a'
  'd'
  'r'
  'k'
  'b'

In [25]:
# проверка эквивалентности двух множеств:
S1 = Set([1,2]);
S2 = Set([3,4]);
issetequal(S1,S2)

false

In [26]:
S3 = Set([1,2,2,3,1,2,3,2,1]);
S4 = Set([2,3,1]);
issetequal(S3,S4)

true

In [27]:
# объединение множеств:
C=union(S1,S2)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [28]:
# пересечение множеств:
D = intersect(S1,S3)

Set{Int64} with 2 elements:
  2
  1

In [29]:
# разность множеств:
E = setdiff(S3,S1)

Set{Int64} with 1 element:
  3

In [30]:
# проверка вхождения элементов одного множества в другое:
issubset(S1,S4)

true

In [31]:
# добавление элемента в множество:
push!(S4, 99)

Set{Int64} with 4 elements:
  2
  99
  3
  1

In [32]:
# удаление последнего элемента множества:
pop!(S4)

2

*Массив* — коллекция упорядоченных элементов, размещённая в многомерной сетке.
Векторы и матрицы являются частными случаями массивов.
Общий синтаксис одномерных массивов:
```
array_name_1 = [element1, element2, ...]
array_name_2 = [element1 element2 ...]
```

Примеры массивов:

In [33]:
# создание пустого массива с абстрактным типом:
empty_array_1 = []

Any[]

In [36]:
# создание пустого массива с конкретным типом:
empty_array_2 = (Int64)[]

Int64[]

In [37]:
# создание пустого массива с конкретным типом:
empty_array_3 = (Float64)[]

Float64[]

In [38]:
# вектор-столбец:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [39]:
# вектор-строка:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [41]:
# многомерные массивы (матрицы):
A = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [42]:
# многомерные массивы (матрицы):
B = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [43]:
# одномерный массив из 8 элементов (массив $1 \times 8$)
# со значениями, случайно распределёнными на интервале [0, 1):
c = rand(1,8)

1×8 Matrix{Float64}:
 0.311174  0.197723  0.132613  0.273034  …  0.339658  0.774617  0.0305637

In [46]:
# многомерный массив $2 \times 3$ (2 строки, 3 столбца) элементов
# со значениями, случайно распределёнными на интервале [0, 1):
C = rand(2,3)

2×3 Matrix{Float64}:
 0.0595642  0.136097  0.551857
 0.966899   0.71968   0.642916

In [47]:
# трёхмерный массив:
D = rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.296321  0.0786156  0.00934994
 0.172244  0.858614   0.0651539
 0.385616  0.997266   0.0670873
 0.451474  0.166293   0.204422

[:, :, 2] =
 0.340121   0.368621  0.401935
 0.0829502  0.482089  0.150628
 0.71259    0.719917  0.762869
 0.861264   0.29391   0.669938

Примеры массивов, заданных некоторыми функциями через включение:

In [48]:
# массив из квадратных корней всех целых чисел от 1 до 10:
roots = [sqrt(i) for i in 1:10]

10-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0
 3.1622776601683795

In [50]:
# массив с элементами вида 3*x^2,
# где x - нечётное число от 1 до 9 (включительно)
ar_1 = [3*i^2 for i in 1:2:9]

5-element Vector{Int64}:
   3
  27
  75
 147
 243

In [51]:
# массив квадратов элементов, если квадрат не делится на 5 или 4:
ar_2=[i^2 for i=1:10 if (i^2%5!=0 && i^2%4!=0)]

4-element Vector{Int64}:
  1
  9
 49
 81

Некоторые операции для работы с массивами:
- ```length(A)``` — число элементов массива A;
- ```ndims(A)``` — число размерностей массива A;
- ```size(A)``` — кортеж размерностей массива A;
- ```size(A, n)``` — размерность массива A в заданном направлении;
- ```copy(A)``` — создание копии массива A;
- ```ones(), zeros()``` — создать массив с единицами или нулями соответственно;
- ```fill(value,array_name)``` — заполнение массива заранее определенным значением;
- ```sort()``` — сортировка элементов;
- ```collect()``` — вернуть массив всех элементов в коллекции или итераторе;
- ```reshape()``` — изменение размера массива;
- ```transpose()``` — транспонирование массива;

Несколько примеров:

In [52]:
# одномерный массив из пяти единиц:
ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [53]:
# двумерный массив 2x3 из единиц:
ones(2,3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [54]:
# одномерный массив из 4 нулей:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [55]:
# заполнить массив 3x2 цифрами 3.5
fill(3.5,(3,2))

3×2 Matrix{Float64}:
 3.5  3.5
 3.5  3.5
 3.5  3.5

In [57]:
# заполнение массива посредством функции repeat():
repeat([1,2],3,3)

6×3 Matrix{Int64}:
 1  1  1
 2  2  2
 1  1  1
 2  2  2
 1  1  1
 2  2  2

In [58]:
# заполнение массива посредством функции repeat():
repeat([1 2],3,3)

3×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 1  2  1  2  1  2

In [59]:
# преобразование одномерного массива из целых чисел от 1 до 12
# в двумерный массив 2x6
a = collect(1:12)
b = reshape(a,(2,6))

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

In [61]:
# транспонирование
b'

6×2 adjoint(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [62]:
# транспонирование
с = transpose(b)

6×2 transpose(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [63]:
# массив 10x5 целых чисел в диапазоне [10, 20]:
ar = rand(10:20, 10, 5)

10×5 Matrix{Int64}:
 18  12  17  12  10
 18  19  11  11  20
 19  18  16  19  13
 13  16  17  20  19
 12  16  16  11  18
 11  14  11  17  20
 15  19  17  14  11
 14  17  18  13  20
 19  17  19  19  14
 12  14  19  14  20

In [64]:
# выбор всех значений строки в столбце 2:
ar[:, 2]

10-element Vector{Int64}:
 12
 19
 18
 16
 16
 14
 19
 17
 17
 14

In [65]:
# выбор всех значений в столбцах 2 и 5:
ar[:, [2, 5]]

10×2 Matrix{Int64}:
 12  10
 19  20
 18  13
 16  19
 16  18
 14  20
 19  11
 17  20
 17  14
 14  20

In [66]:
# все значения строк в столбцах 2, 3 и 4:
ar[:, 2:4]

10×3 Matrix{Int64}:
 12  17  12
 19  11  11
 18  16  19
 16  17  20
 16  16  11
 14  11  17
 19  17  14
 17  18  13
 17  19  19
 14  19  14

In [67]:
# значения в строках 2, 4, 6 и в столбцах 1 и 5:
ar[[2, 4, 6], [1, 5]]

3×2 Matrix{Int64}:
 18  20
 13  19
 11  20

In [68]:
# значения в строке 1 от столбца 3 до последнего столбца:
ar[1, 3:end]

3-element Vector{Int64}:
 17
 12
 10

In [70]:
# сортировка по столбцам:
sort(ar,dims=1)

10×5 Matrix{Int64}:
 11  12  11  11  10
 12  14  11  11  11
 12  14  16  12  13
 13  16  16  13  14
 14  16  17  14  18
 15  17  17  14  19
 18  17  17  17  20
 18  18  18  19  20
 19  19  19  19  20
 19  19  19  20  20

In [71]:
# сортировка по строкам:
sort(ar,dims=2)

10×5 Matrix{Int64}:
 10  12  12  17  18
 11  11  18  19  20
 13  16  18  19  19
 13  16  17  19  20
 11  12  16  16  18
 11  11  14  17  20
 11  14  15  17  19
 13  14  17  18  20
 14  17  19  19  19
 12  14  14  19  20

In [72]:
# поэлементное сравнение с числом
# (результат - массив логических значений):
ar .> 14

10×5 BitMatrix:
 1  0  1  0  0
 1  1  0  0  1
 1  1  1  1  0
 0  1  1  1  1
 0  1  1  0  1
 0  0  0  1  1
 1  1  1  0  0
 0  1  1  0  1
 1  1  1  1  0
 0  0  1  0  1

In [73]:
# возврат индексов элементов массива, удовлетворяющих условию:
findall(ar .> 14)

30-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 1)
 CartesianIndex(3, 1)
 CartesianIndex(7, 1)
 CartesianIndex(9, 1)
 CartesianIndex(2, 2)
 CartesianIndex(3, 2)
 CartesianIndex(4, 2)
 CartesianIndex(5, 2)
 CartesianIndex(7, 2)
 CartesianIndex(8, 2)
 CartesianIndex(9, 2)
 CartesianIndex(1, 3)
 ⋮
 CartesianIndex(9, 3)
 CartesianIndex(10, 3)
 CartesianIndex(3, 4)
 CartesianIndex(4, 4)
 CartesianIndex(6, 4)
 CartesianIndex(9, 4)
 CartesianIndex(2, 5)
 CartesianIndex(4, 5)
 CartesianIndex(5, 5)
 CartesianIndex(6, 5)
 CartesianIndex(8, 5)
 CartesianIndex(10, 5)

**Задания для самостоятельного выполнения**

**Задание №1**

Даны множества: 𝐴 = {0, 3, 4, 9}, 𝐵 = {1, 3, 4, 7}, 𝐶 = {0, 1, 2, 4, 7, 8, 9}. Найти P = 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐶 ∪ 𝐵 ∩ 𝐶.

In [76]:
A = Set([0, 3, 4, 9]);
B = Set([1, 3, 4, 7]);
C = Set([0, 1, 2, 4, 7, 8, 9]);
P = union(intersect(A, B), intersect(A, B), intersect(A, C), intersect(B, C))

Set{Int64} with 6 elements:
  0
  4
  7
  9
  3
  1

**Задание №2**

Приведите свои примеры с выполнением операций над множествами элементов разных типов.

In [77]:
Set1 = Set([13, 67, 3, "Katya"])

Set{Any} with 4 elements:
  13
  67
  3
  "Katya"

In [79]:
println("\nЭлементы множества:")
for i in Set1
    println(i)
end


Элементы множества:
13
67
3
Katya


In [80]:
println(in("Katya", Set1))

true


In [85]:
Set1 = push!(Set1, "Super")
println("\nМножество после добавления одного элемента:\n", Set1)


Множество после добавления одного элемента:
Set(Any[13, 67, "Super", 3, "Katya"])


In [86]:
for i in 1:4
    push!(Set1, i)
end
println("\nМножество после добавления диапазона элементов:\n", Set1)


Множество после добавления диапазона элементов:
Set(Any[13, 4, 67, "Super", 2, 3, "Katya", 1])


**Задание №3**

Создать массив разными способами

In [89]:
a_1 = [i for i in 1:25]
print(a_1, '\n')

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


In [91]:
b_1 = reverse([i for i in 1:25])
print(b_1, '\n')

[25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [92]:
c_1 = vcat(a_1, b_1)
print(c_1, '\n')

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [93]:
tmp = [4, 6, 3]
print(tmp, '\n')

[4, 6, 3]


In [96]:
println(vcat(fill.(tmp, [10, 1, 1])...))

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 3]


In [97]:
println(vcat(fill.(tmp, [10, 10, 10])...))

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [98]:
println(vcat(fill.(tmp, [11, 10, 10])...))

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [99]:
println(vcat(fill.(tmp, [10, 20, 30])...))

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]


In [102]:
tmp_1 = []
for i in 1:3
    push!(tmp_1, 2^tmp[i])
end
println(vcat(fill.(tmp_1, [1, 1, 4])...))
count = 0
for i in tmp_1
    if '6' in string(i)
        count += 1
    end
end
println(count)

[16, 64, 8, 8, 8, 8]
2


In [103]:
using Statistics
y(x) = exp(x)*cos(x)
Y = [y(x) for x in 3:0.1:6]
mean(Y)

53.11374594642971

In [109]:
vect = []
for j in 1:3:34
    i = j + 2
    push!(vect, ((0.1)^i, (0.2)^j))
end
println(vect)

Any[(0.0010000000000000002, 0.2), (1.0000000000000004e-6, 0.0016000000000000003), (1.0000000000000005e-9, 1.2800000000000006e-5), (1.0000000000000008e-12, 1.0240000000000006e-7), (1.0000000000000009e-15, 8.192000000000005e-10), (1.0000000000000008e-18, 6.5536000000000055e-12), (1.0000000000000012e-21, 5.2428800000000056e-14), (1.0000000000000012e-24, 4.194304000000005e-16), (1.0000000000000015e-27, 3.3554432000000044e-18), (1.0000000000000017e-30, 2.684354560000004e-20), (1.0000000000000018e-33, 2.147483648000004e-22), (1.000000000000002e-36, 1.7179869184000035e-24)]


In [110]:
vect_1 = [(2^i)/i for i in 1:25]
println(vect_1)

[2.0, 2.0, 2.6666666666666665, 4.0, 6.4, 10.666666666666666, 18.285714285714285, 32.0, 56.888888888888886, 102.4, 186.1818181818182, 341.3333333333333, 630.1538461538462, 1170.2857142857142, 2184.5333333333333, 4096.0, 7710.117647058823, 14563.555555555555, 27594.105263157893, 52428.8, 99864.38095238095, 190650.18181818182, 364722.0869565217, 699050.6666666666, 1.34217728e6]


In [111]:
vect_2 = []
for i in 1:30
    push!(vect_2, "fn$i")
end
println(vect_2)

Any["fn1", "fn2", "fn3", "fn4", "fn5", "fn6", "fn7", "fn8", "fn9", "fn10", "fn11", "fn12", "fn13", "fn14", "fn15", "fn16", "fn17", "fn18", "fn19", "fn20", "fn21", "fn22", "fn23", "fn24", "fn25", "fn26", "fn27", "fn28", "fn29", "fn30"]


In [112]:
vect_x = []
for i in 1:250
    push!(vect_x, rand(0:999))
end
println(vect_x)

vect_y = []
for i in 1:250
    push!(vect_y, rand(0:999))
end
println(vect_y)

Any[567, 705, 144, 963, 254, 810, 474, 111, 517, 935, 978, 415, 348, 497, 792, 353, 3, 962, 85, 994, 248, 677, 806, 933, 178, 511, 410, 597, 216, 954, 525, 770, 202, 686, 575, 48, 695, 148, 959, 678, 380, 644, 692, 286, 928, 474, 752, 686, 919, 27, 134, 517, 294, 915, 717, 65, 720, 202, 256, 388, 318, 423, 860, 350, 768, 187, 429, 683, 733, 790, 601, 56, 998, 901, 283, 14, 771, 411, 101, 675, 506, 699, 523, 33, 121, 110, 480, 617, 927, 189, 263, 194, 570, 656, 347, 971, 643, 736, 511, 336, 77, 392, 753, 992, 637, 828, 911, 556, 934, 400, 822, 90, 672, 201, 248, 611, 909, 704, 547, 963, 779, 559, 282, 979, 651, 126, 188, 412, 325, 856, 554, 616, 456, 766, 615, 158, 123, 712, 418, 469, 864, 489, 137, 951, 821, 440, 272, 879, 529, 159, 746, 66, 989, 205, 315, 201, 422, 777, 360, 391, 463, 275, 86, 618, 975, 41, 470, 766, 821, 689, 367, 826, 707, 521, 831, 82, 855, 397, 435, 620, 171, 66, 338, 499, 745, 408, 628, 900, 80, 890, 963, 802, 279, 107, 589, 996, 291, 696, 151, 310, 404, 560, 290

In [116]:
vect_3 = []
for i in 1:249
    j = i + 1
    push!(vect_3, vect_y[j] - vect_x[i])
end
println(vect_3)

Any[-201, -476, 149, -592, 504, -798, -240, 523, -41, -584, -228, -234, 551, 22, -775, -271, 852, -331, 416, -918, 372, -53, -364, -371, 689, -460, 248, -419, 423, -462, -282, -382, 717, 44, 224, 876, 28, 705, -532, -638, -310, -632, -507, 466, -92, -98, 31, 281, -327, 4, 759, -174, 466, -558, -699, -4, 50, 494, -46, 241, 494, 158, -284, 628, -689, 646, 205, 82, -328, -38, 171, 340, -536, -637, 295, 877, -504, -287, 98, 267, -55, -203, 400, 594, 130, 854, 188, -581, -237, 186, -35, 717, 85, -568, -100, -377, -308, -557, -470, -131, -31, -355, 225, -151, -102, -309, -500, -180, -320, 48, 149, 826, -111, -60, 738, -389, -706, -239, 179, -716, -581, 116, -104, -496, 311, 799, -151, -396, -213, -415, -21, 185, -283, 78, -205, 176, 457, -449, 543, 112, -702, -158, 218, -524, -21, 387, 625, -814, -521, 494, -508, 5, -320, 655, -297, 153, -409, -117, 62, 152, -393, 638, 190, 19, -614, 798, -16, 26, -615, -439, 39, -302, -523, -188, -726, 806, -486, -376, 143, -207, 403, 170, 187, -392, -703, 

In [117]:
vect_4 = []
for i in 1:248
    j = i + 1
    push!(vect_4, vect_x[i] + 2*vect_x[i + 1] - vect_x[i + 2])
end
println(vect_4)

Any[1833, 30, 1816, 661, 1400, 1647, 179, 210, 1409, 2476, 1460, 614, 550, 1728, 1495, -603, 1842, 138, 1825, 813, 796, 1356, 2494, 778, 790, 734, 1388, 75, 1599, 1234, 1863, 488, 999, 1788, -24, 1290, 32, 1388, 1935, 794, 976, 1742, 336, 1668, 1124, 1292, 1205, 2497, 839, -222, 874, 190, 1407, 2284, 127, 1303, 868, 326, 714, 601, 304, 1793, 792, 1699, 713, 362, 1062, 1359, 1712, 1936, -285, 1151, 2517, 1453, -460, 1145, 1492, -62, 945, 988, 1381, 1712, 468, 165, -139, 453, 787, 2282, 1042, 521, 81, 678, 1535, 379, 1646, 1521, 1604, 1422, 1106, 98, 108, 906, 2100, 1438, 1382, 2094, 1089, 2024, 912, 1954, 330, 1233, 826, 86, 561, 1725, 1770, 835, 1694, 1962, 1615, 144, 1589, 2155, 715, 90, 687, 206, 1483, 1348, 1330, 762, 1373, 1838, 808, -308, 1129, 1079, 492, 1708, 1705, -188, 1218, 2153, 1429, 105, 1501, 1778, 101, 1585, -111, 1839, 1084, 634, 295, 268, 1616, 1106, 679, 1042, 927, -171, 347, 2527, 587, 215, 1181, 1719, 1832, 597, 1312, 1719, 918, 2101, 140, 1395, 1214, 647, 1504, 896

In [118]:
vect_5 = []
for i in 1:249
    j = i + 1
    push!(vect_5, sin(vect_y[i])/cos(vect_x[j]))
end
println(vect_5)

Any[0.21843959301371277, 1.14789996675825, -3.2452441627476594, 0.8286834886906903, 0.33389271789828784, 0.827471966480573, 1.067712632615006, -4.836610105568404, -1.5408159457455664, 1.753301412621282, -0.7946028752973443, -0.9882625689938298, -1.1575530816498203, 0.5089940999047953, -1.4297746503043425, 0.9711159379297504, 0.40045892987177684, -0.47522302699283503, 1.4373773722927636, 1.0139262908348727, -42.83351774003122, 4.953321087148344, -0.9247346861392144, -1.7140888897950843, -0.7171757714239853, 3.5875266568803106, 0.6734206676125903, 1.3741753676771638, 1.7459929347427572, 1.0139543699257147, -0.9896154166621259, -1.5050584409772634, -2.3575899780181793, -1.000380561488695, -1.426193743375484, -1.132234090367493, -0.386020687101948, -0.6121926240376945, -1.196684434703908, 0.25604566597904244, -0.7453747461058132, 1.172079610339363, 0.5401449401566571, -1.037538996005377, 0.9871436941460947, -0.8252636423683629, -1.9726266790145126, 8.052587295421466, 1.9624499099848787, -2

In [120]:
summa = 0
for i in 1: 249
    summa += exp(-vect_x[i + 1])/(vect_x[i] + 10)
end 
print(summa)

0.0005222704915505417

In [122]:
y_sorted = sort(vect_y)
for i in y_sorted
    if i > 600
        print(i, "; ")
    end
end
println('\n', "Индексы:")
show(findall(vect_y .> 600))

601; 614; 620; 624; 624; 627; 628; 629; 631; 631; 634; 634; 637; 639; 653; 653; 655; 658; 660; 668; 669; 675; 690; 696; 698; 723; 726; 728; 730; 739; 742; 747; 750; 752; 752; 758; 760; 761; 765; 770; 772; 772; 779; 781; 783; 792; 799; 800; 801; 812; 825; 826; 827; 833; 834; 836; 839; 841; 844; 853; 855; 860; 863; 867; 869; 888; 891; 893; 897; 899; 911; 913; 915; 916; 919; 919; 923; 924; 925; 927; 942; 961; 962; 963; 964; 967; 970; 971; 971; 978; 978; 986; 986; 
Индексы:
[6, 9, 12, 14, 18, 19, 22, 23, 26, 28, 30, 34, 35, 36, 37, 38, 39, 45, 46, 48, 49, 52, 54, 58, 59, 61, 62, 65, 67, 68, 69, 71, 72, 77, 81, 84, 85, 87, 88, 90, 93, 94, 104, 105, 110, 112, 113, 116, 120, 123, 126, 127, 133, 135, 140, 146, 147, 148, 151, 154, 155, 159, 163, 165, 167, 169, 177, 187, 188, 192, 193, 195, 198, 201, 202, 203, 207, 210, 212, 217, 219, 221, 222, 227, 233, 236, 238, 239, 242, 243, 244, 245, 248]

In [123]:
for i in 1:length(vect_y)
    if (vect_y[i] > 600)
        print(vect_x[i], "; ")
    end
end

810; 517; 415; 497; 962; 85; 677; 806; 511; 597; 954; 686; 575; 48; 695; 148; 959; 928; 474; 686; 919; 517; 915; 202; 256; 318; 423; 768; 429; 683; 733; 601; 56; 771; 506; 33; 121; 480; 617; 189; 570; 656; 992; 637; 400; 90; 672; 611; 963; 282; 126; 188; 456; 615; 469; 440; 272; 879; 746; 205; 315; 360; 86; 975; 470; 821; 855; 628; 900; 802; 279; 589; 696; 404; 560; 290; 804; 985; 153; 372; 406; 1; 880; 742; 334; 656; 182; 497; 794; 791; 93; 697; 516; 

In [124]:
vect_6 = []
for i in vect_x
    push!(vect_6, abs(i - mean(vect_x))^(1/2))
end
print(vect_6)

Any[7.368039087844202, 13.866794871202213, 19.201874908456205, 21.21999057492722, 16.084526726018392, 17.242041642450584, 6.2218968168879165, 20.042754301742065, 2.0707486568871682, 20.549647198918038, 21.570535459278705, 9.884938037236248, 12.834017297791053, 3.963836525387997, 16.71191191934663, 12.637721313591307, 22.576802253640793, 21.196414791185795, 20.68119919153626, 21.938277051765027, 16.269972341709742, 12.817488053436993, 17.125653272211252, 20.500926808317715, 18.29513596560572, 1.308434178703686, 10.134692891252305, 9.180849633884655, 17.225330185514586, 21.00685602368903, 3.5054243680330646, 16.040199500006228, 17.627024706398977, 13.163890002579025, 7.892274703784708, 21.557179778440407, 13.501407334052255, 19.097434382659888, 21.12552957916085, 12.85643807592134, 11.520069444235133, 11.458097573332147, 13.389846899796876, 15.056958524217299, 20.378616243503874, 6.2218968168879165, 15.468936615035954, 13.163890002579025, 20.156587012686447, 22.0388747444147, 19.46052414

In [125]:
count = 0
for i in vect_y
    if abs(maximum(vect_y) - i) <= 200
        count += 1
    end
end
print(count)

48

In [127]:
sum_even = 0
sum_odd = 0
for i in vect_x
    if (i % 2) == 0
        sum_even += 1
    else
        sum_odd += 1
    end
end
println("Количество чётных элементов вектора x: ", sum_even)
println("Количество нечётных элементов вектора x: ", sum_odd)

Количество чётных элементов вектора x: 130
Количество нечётных элементов вектора x: 120


In [128]:
sum_seven = 0
for i in vect_x
    if (i % 7) == 0
        sum_seven += 1
    end
end
println("Количество элементов вектора x кратных 7: ", sum_seven)

Количество элементов вектора x кратных 7: 38


In [129]:
print(vect_x)

Any[567, 705, 144, 963, 254, 810, 474, 111, 517, 935, 978, 415, 348, 497, 792, 353, 3, 962, 85, 994, 248, 677, 806, 933, 178, 511, 410, 597, 216, 954, 525, 770, 202, 686, 575, 48, 695, 148, 959, 678, 380, 644, 692, 286, 928, 474, 752, 686, 919, 27, 134, 517, 294, 915, 717, 65, 720, 202, 256, 388, 318, 423, 860, 350, 768, 187, 429, 683, 733, 790, 601, 56, 998, 901, 283, 14, 771, 411, 101, 675, 506, 699, 523, 33, 121, 110, 480, 617, 927, 189, 263, 194, 570, 656, 347, 971, 643, 736, 511, 336, 77, 392, 753, 992, 637, 828, 911, 556, 934, 400, 822, 90, 672, 201, 248, 611, 909, 704, 547, 963, 779, 559, 282, 979, 651, 126, 188, 412, 325, 856, 554, 616, 456, 766, 615, 158, 123, 712, 418, 469, 864, 489, 137, 951, 821, 440, 272, 879, 529, 159, 746, 66, 989, 205, 315, 201, 422, 777, 360, 391, 463, 275, 86, 618, 975, 41, 470, 766, 821, 689, 367, 826, 707, 521, 831, 82, 855, 397, 435, 620, 171, 66, 338, 499, 745, 408, 628, 900, 80, 890, 963, 802, 279, 107, 589, 996, 291, 696, 151, 310, 404, 560, 290

In [130]:
print(vect_y)

Any[509, 366, 229, 293, 371, 758, 12, 234, 634, 476, 351, 750, 181, 899, 519, 17, 82, 855, 631, 501, 76, 620, 624, 442, 562, 867, 51, 658, 178, 639, 492, 243, 388, 919, 730, 799, 924, 723, 853, 427, 40, 70, 12, 185, 752, 836, 376, 783, 967, 592, 31, 893, 343, 760, 357, 18, 61, 770, 696, 210, 629, 812, 581, 576, 978, 79, 833, 634, 765, 405, 752, 772, 396, 462, 264, 578, 891, 267, 124, 199, 942, 451, 496, 923, 627, 251, 964, 668, 36, 690, 375, 228, 911, 655, 88, 247, 594, 335, 179, 41, 205, 46, 37, 978, 841, 535, 519, 411, 376, 614, 448, 971, 916, 561, 141, 986, 222, 203, 465, 726, 247, 198, 675, 178, 483, 962, 925, 37, 16, 112, 441, 533, 801, 173, 844, 410, 334, 580, 263, 961, 581, 162, 331, 355, 427, 800, 827, 897, 65, 8, 653, 238, 71, 669, 860, 18, 354, 13, 660, 422, 543, 70, 913, 276, 637, 361, 839, 454, 792, 206, 250, 406, 524, 184, 333, 105, 888, 369, 21, 578, 413, 574, 236, 525, 107, 42, 628, 863, 433, 559, 576, 971, 927, 305, 739, 417, 481, 653, 256, 499, 631, 963, 728, 223, 111,

In [133]:
p = sortperm(vect_y)
vect_x_sorted = vect_x[p]

250-element Vector{Any}:
 345
 159
 474
 692
 777
 325
 353
  65
 201
 164
 435
 134
 927
   ⋮
 469
 126
 560
 480
 919
 406
  90
 802
 768
 992
 611
 656

In [134]:
reverse(last(sort(vect_x), 10))

10-element Vector{Any}:
 998
 996
 994
 992
 989
 985
 979
 978
 975
 971

In [136]:
x_sorted = sort(vect_x)
print(x_sorted)

Any[1, 3, 8, 9, 14, 22, 23, 25, 27, 33, 37, 41, 48, 56, 65, 66, 66, 77, 80, 82, 85, 86, 90, 93, 101, 107, 110, 111, 121, 123, 126, 134, 137, 144, 144, 145, 148, 151, 153, 158, 159, 164, 171, 178, 182, 187, 188, 189, 194, 201, 201, 202, 202, 205, 216, 232, 248, 248, 254, 256, 263, 272, 275, 279, 282, 283, 286, 286, 290, 291, 294, 310, 315, 318, 325, 327, 331, 334, 336, 338, 341, 345, 347, 348, 350, 353, 360, 367, 372, 380, 388, 391, 392, 397, 400, 404, 406, 408, 410, 411, 412, 415, 416, 418, 422, 423, 429, 435, 440, 456, 463, 469, 470, 474, 474, 480, 489, 497, 497, 499, 506, 511, 511, 516, 517, 517, 521, 523, 525, 529, 532, 541, 547, 554, 556, 559, 560, 567, 570, 575, 589, 597, 601, 602, 611, 615, 616, 617, 618, 620, 620, 628, 636, 637, 643, 644, 651, 656, 656, 672, 675, 677, 678, 683, 686, 686, 689, 692, 695, 696, 697, 699, 704, 705, 707, 708, 712, 717, 720, 733, 736, 742, 745, 746, 752, 753, 766, 766, 766, 768, 770, 771, 777, 779, 790, 791, 792, 794, 802, 804, 806, 806, 807, 810, 821,

In [137]:
show(unique(x_sorted))

Any[1, 3, 8, 9, 14, 22, 23, 25, 27, 33, 37, 41, 48, 56, 65, 66, 77, 80, 82, 85, 86, 90, 93, 101, 107, 110, 111, 121, 123, 126, 134, 137, 144, 145, 148, 151, 153, 158, 159, 164, 171, 178, 182, 187, 188, 189, 194, 201, 202, 205, 216, 232, 248, 254, 256, 263, 272, 275, 279, 282, 283, 286, 290, 291, 294, 310, 315, 318, 325, 327, 331, 334, 336, 338, 341, 345, 347, 348, 350, 353, 360, 367, 372, 380, 388, 391, 392, 397, 400, 404, 406, 408, 410, 411, 412, 415, 416, 418, 422, 423, 429, 435, 440, 456, 463, 469, 470, 474, 480, 489, 497, 499, 506, 511, 516, 517, 521, 523, 525, 529, 532, 541, 547, 554, 556, 559, 560, 567, 570, 575, 589, 597, 601, 602, 611, 615, 616, 617, 618, 620, 628, 636, 637, 643, 644, 651, 656, 672, 675, 677, 678, 683, 686, 689, 692, 695, 696, 697, 699, 704, 705, 707, 708, 712, 717, 720, 733, 736, 742, 745, 746, 752, 753, 766, 768, 770, 771, 777, 779, 790, 791, 792, 794, 802, 804, 806, 807, 810, 821, 822, 826, 828, 831, 855, 856, 860, 863, 864, 868, 879, 880, 890, 900, 901, 909

**Задание №4**

Создайте массив squares, в котором будут храниться квадраты всех целых чисел от 1 до 100.

In [138]:
squares = [(i)^2 for i in 1:100]
print(squares)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]

**Задание №5**

Подключите пакет Primes (функции для вычисления простых чисел). Сгенерируйте
массив myprimes, в котором будут храниться первые 168 простых чисел. Определите
89-е наименьшее простое число. Получите срез массива с 89-го до 99-го элемента
включительно, содержащий наименьшие простые числа.

In [140]:
import Pkg
Pkg.add("Primes")

   Resolving package versions...
     Project No packages added to or removed from `~/.julia/environments/v1.12/Project.toml`
    Manifest No packages added to or removed from `~/.julia/environments/v1.12/Manifest.toml`


In [144]:
using Primes
myprimes = primes(prime(168))
print(myprimes)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]

In [145]:
myprimes[89]

461

In [146]:
myprimes[89:99]

11-element Vector{Int64}:
 461
 463
 467
 479
 487
 491
 499
 503
 509
 521
 523

**Задание №6**

Вычислить выражения

In [150]:
sum_61 = 0
for i in 10:100
    sum_61 += i^3 + 4*i^2
end
print(sum_61)

26852735

In [149]:
M = 25
sum_62 = 0
for i in 1:M
    sum_62 += (2^(i)/i) + (3^(i)/i^2)
end
print(sum_62)

2.1291704368143802e9

In [152]:
N = 38
sum_63 = 1
a_n = 1
for i in 2:2:N
    a_n *= i/(i+1)
    sum_63 += a_n
end
print(sum_63)

6.976346137897618