In [ ]:
2+3

In [ ]:
1+2

In [ ]:
3+5

In [ ]:
?println

In [ ]:
println("Hello, world")

In [ ]:
;date

In [ ]:
;whoami

In [8]:
typeof(3), typeof(3.5), typeof(3/3.5), typeof(sqrt(3+4im)), typeof(pi)

(Int64, Float64, Float64, ComplexF64, Irrational{:π})

In [10]:
1.0/0.0, 1.0/(-0.0), 0.0/0.0

(Inf, -Inf, NaN)

In [11]:
for T in
    [Int8,Int16,Int32,Int64,Int128,UInt8,UInt16,UInt32,UInt64,UInt128]
println("$(lpad(T,7)): [$(typemin(T)),$(typemax(T))]")
end

   Int8: [-128,127]
  Int16: [-32768,32767]
  Int32: [-2147483648,2147483647]
  Int64: [-9223372036854775808,9223372036854775807]
 Int128: [-170141183460469231731687303715884105728,170141183460469231731687303715884105727]
  UInt8: [0,255]
 UInt16: [0,65535]
 UInt32: [0,4294967295]
 UInt64: [0,18446744073709551615]
UInt128: [0,340282366920938463463374607431768211455]


In [12]:
Int64(2.0), Char(2)

(2, '\x02')

In [13]:
convert(Int64, 2.0), convert(Char,2)

(2, '\x02')

In [14]:
typeof(promote(Int8(1), Float16(4.5), Float32(4.1)))

Tuple{Float32, Float32, Float32}

In [15]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [16]:
f(4)

16

In [17]:
f(3)

9

In [18]:
g(x) = x^2

g (generic function with 1 method)

In [19]:
g(8)

64

In [20]:
g(13)

169

In [21]:
g(67)

4489

In [22]:
a = [4 7 6] # вектор-строка
b = [1, 2, 3] # вектор-столбец
a[2], b[2] # вторые элементы векторов a и b

(7, 2)

In [24]:
a = 1; b = 2; c = 3; d = 4 # присвоение значений
Am = [a b; c d] # матрица 2 х 2

2×2 Matrix{Int64}:
 1  2
 3  4

In [25]:
Am[1,1], Am[1,2], Am[2,1], Am[2,2] # элементы матрицы

(1, 2, 3, 4)

In [29]:
aa = [1 2]
AA = [1 2; 3 4]
aa, AA, aa'

([1 2], [1 2; 3 4], [1; 2;;])

In [31]:
aa*AA*aa'

1×1 Matrix{Int64}:
 27

In [32]:
?read

search: read read! rpad real break readdir isready Threads rem secd end repr



```julia
read(command::Cmd, String)
```

Run `command` and return the resulting output as a `String`.

---

```julia
read(command::Cmd)
```

Run `command` and return the resulting output as an array of bytes.

---

```julia
read(s::IOStream, nb::Integer; all=true)
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

If `all` is `true` (the default), this function will block repeatedly trying to read all requested bytes, until an error or end-of-file occurs. If `all` is `false`, at most one `read` call is performed, and the amount of data returned is device-dependent. Note that not all stream types support the `all` option.

---

```julia
read(s::IO, nb=typemax(Int))
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

---

```julia
read(filename::AbstractString)
```

Read the entire contents of a file as a `Vector{UInt8}`.

```julia
read(filename::AbstractString, String)
```

Read the entire contents of a file as a string.

```julia
read(filename::AbstractString, args...)
```

Open a file and read its contents. `args` is passed to `read`: this is equivalent to `open(io->read(io, args...), filename)`.

---

```julia
read(io::IO, T)
```

Read a single value of type `T` from `io`, in canonical binary representation.

Note that Julia does not convert the endianness for you. Use [`ntoh`](@ref) or [`ltoh`](@ref) for this purpose.

```julia
read(io::IO, String)
```

Read the entirety of `io`, as a `String` (see also [`readchomp`](@ref)).

# Examples

```jldoctest
julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, Char)
'J': ASCII/Unicode U+004A (category Lu: Letter, uppercase)

julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, String)
"JuliaLang is a GitHub organization"
```


In [33]:
?readdlm

search: readdir read! read real readchomp isreadable isreadonly readeach

Couldn't find readdlm
Perhaps you meant readdir, real, read, read! or readchomp


No documentation found.

Binding `readdlm` does not exist.


In [40]:
n = open("test.txt", "r")

IOStream(<file test.txt>)

In [41]:
read(n, String)

"Hello\nmy\nname\nis\nKatya"

In [43]:
n = open("test.txt", "r")

IOStream(<file test.txt>)

In [44]:
readline(n)

"Hello"

In [45]:
n = open("test.txt", "r")

IOStream(<file test.txt>)

In [46]:
readlines(n)

5-element Vector{String}:
 "Hello"
 "my"
 "name"
 "is"
 "Katya"

In [56]:
?show

search: show @show throw chown Cshort ispow2 showable chop



```julia
show([io::IO = stdout], x)
```

Write a text representation of a value `x` to the output stream `io`. New types `T` should overload `show(io::IO, x::T)`. The representation used by `show` generally includes Julia-specific formatting and type information, and should be parseable Julia code when possible.

[`repr`](@ref) returns the output of `show` as a string.

For a more verbose human-readable text output for objects of type `T`, define `show(io::IO, ::MIME"text/plain", ::T)` in addition. Checking the `:compact` [`IOContext`](@ref) key (often checked as `get(io, :compact, false)::Bool`) of `io` in such methods is recommended, since some containers show their elements by calling this method with `:compact => true`.

See also [`print`](@ref), which writes un-decorated representations.

# Examples

```jldoctest
julia> show("Hello World!")
"Hello World!"
julia> print("Hello World!")
Hello World!
```

---

```julia
show(io::IO, mime, x)
```

The [`display`](@ref) functions ultimately call `show` in order to write an object `x` as a given `mime` type to a given I/O stream `io` (usually a memory buffer), if possible. In order to provide a rich multimedia representation of a user-defined type `T`, it is only necessary to define a new `show` method for `T`, via: `show(io, ::MIME"mime", x::T) = ...`, where `mime` is a MIME-type string and the function body calls [`write`](@ref) (or similar) to write that representation of `x` to `io`. (Note that the `MIME""` notation only supports literal strings; to construct `MIME` types in a more flexible manner use `MIME{Symbol("")}`.)

For example, if you define a `MyImage` type and know how to write it to a PNG file, you could define a function `show(io, ::MIME"image/png", x::MyImage) = ...` to allow your images to be displayed on any PNG-capable `AbstractDisplay` (such as IJulia). As usual, be sure to `import Base.show` in order to add new methods to the built-in Julia function `show`.

Technically, the `MIME"mime"` macro defines a singleton type for the given `mime` string, which allows us to exploit Julia's dispatch mechanisms in determining how to display objects of any given type.

The default MIME type is `MIME"text/plain"`. There is a fallback definition for `text/plain` output that calls `show` with 2 arguments, so it is not always necessary to add a method for that case. If a type benefits from custom human-readable output though, `show(::IO, ::MIME"text/plain", ::T)` should be defined. For example, the `Day` type uses `1 day` as the output for the `text/plain` MIME type, and `Day(1)` as the output of 2-argument `show`.

# Examples

```jldoctest
julia> struct Day
           n::Int
       end

julia> Base.show(io::IO, ::MIME"text/plain", d::Day) = print(io, d.n, " day")

julia> Day(1)
1 day
```

Container types generally implement 3-argument `show` by calling `show(io, MIME"text/plain"(), x)` for elements `x`, with `:compact => true` set in an [`IOContext`](@ref) passed as the first argument.


In [48]:
using DelimitedFiles
n = open("test2.txt", "r")
readdlm(n)

3×3 Matrix{Any}:
 "X,"    "Y,"     "Z"
 "1.0,"  "2.0,"  3.0
 "4.0,"  "5.0,"  6.0

In [49]:
using DelimitedFiles
n = open("test2.txt", "r")
read(n)

35-element Vector{UInt8}:
 0x58
 0x2c
 0x20
 0x59
 0x2c
 0x20
 0x5a
 0x0a
 0x31
 0x2e
 0x30
 0x2c
 0x20
    ⋮
 0x2e
 0x30
 0x2c
 0x20
 0x35
 0x2e
 0x30
 0x2c
 0x20
 0x36
 0x2e
 0x30

In [54]:
for i in 1:4
    print(i)
end

1234

In [55]:
for i in 1:4
    println(i)
end

1
2
3
4


In [57]:
show("Katya")

"Katya"

In [58]:
print("Katya")

Katya

In [59]:
?parse()

```julia
parse(type, str; base)
```

Parse a string as a number. For `Integer` types, a base can be specified (the default is 10). For floating-point types, the string is parsed as a decimal floating-point number.  `Complex` types are parsed from decimal strings of the form `"R±Iim"` as a `Complex(R,I)` of the requested type; `"i"` or `"j"` can also be used instead of `"im"`, and `"R"` or `"Iim"` are also permitted. If the string does not contain a valid number, an error is raised.

!!! compat "Julia 1.1"
    `parse(Bool, str)` requires at least Julia 1.1.


# Examples

```jldoctest
julia> parse(Int, "1234")
1234

julia> parse(Int, "1234", base = 5)
194

julia> parse(Int, "afc", base = 16)
2812

julia> parse(Float64, "1.2e-3")
0.0012

julia> parse(Complex{Float64}, "3.2e-1 + 4.5im")
0.32 + 4.5im
```

---

```julia
parse(::Type{Platform}, triplet::AbstractString)
```

Parses a string platform triplet back into a `Platform` object.

---

```julia
parse(::Type{SimpleColor}, rgb::String)
```

An analogue of `tryparse(SimpleColor, rgb::String)` (which see), that raises an error instead of returning `nothing`.


In [60]:
?write()

```julia
write(filename::AbstractString, content)
```

Write the canonical binary representation of `content` to a file, which will be created if it does not exist yet or overwritten if it does exist.

Return the number of bytes written into the file.

---

```julia
write(io::IO, x)
```

Write the canonical binary representation of a value to the given I/O stream or file. Return the number of bytes written into the stream. See also [`print`](@ref) to write a text representation (with an encoding that may depend upon `io`).

The endianness of the written value depends on the endianness of the host system. Convert to/from a fixed endianness when writing/reading (e.g. using  [`htol`](@ref) and [`ltoh`](@ref)) to get results that are consistent across platforms.

You can write multiple values with the same `write` call, i.e. the following are equivalent:

```julia
write(io, x, y...)
write(io, x) + write(io, y...)
```

# Examples

Consistent serialization:

```jldoctest
julia> fname = tempname(); # random temporary filename

julia> open(fname,"w") do f
           # Make sure we write 64bit integer in little-endian byte order
           write(f,htol(Int64(42)))
       end
8

julia> open(fname,"r") do f
           # Convert back to host byte order and host integer type
           Int(ltoh(read(f,Int64)))
       end
42
```

Merging write calls:

```jldoctest
julia> io = IOBuffer();

julia> write(io, "JuliaLang is a GitHub organization.", " It has many members.")
56

julia> String(take!(io))
"JuliaLang is a GitHub organization. It has many members."

julia> write(io, "Sometimes those members") + write(io, " write documentation.")
44

julia> String(take!(io))
"Sometimes those members write documentation."
```

User-defined plain-data types without `write` methods can be written when wrapped in a `Ref`:

```jldoctest
julia> struct MyStruct; x::Float64; end

julia> io = IOBuffer()
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1)

julia> write(io, Ref(MyStruct(42.0)))
8

julia> seekstart(io); read!(io, Ref(MyStruct(NaN)))
Base.RefValue{MyStruct}(MyStruct(42.0))
```


In [1]:
io = IOBuffer();

In [2]:
write(io, "Hello.", " My name is Katya")

23

In [3]:
write(io, "Hello.") + write(io, " My name is Katya")

23

In [4]:
String(take!(io))

"Hello. My name is KatyaHello. My name is Katya"

In [5]:
parse(Int, "13")

13

In [6]:
parse(Int, "1101", base = 2)

13

In [7]:
parse(Int, "1a6f", base = 16)

6767

In [8]:
parse(Float64, "314e-2")

3.14

In [15]:
a = 2 + 1
b = 3 * 1.2
c = "Katya " * "hello"
println(a, '\n', b, '\n', c)

3
3.5999999999999996
Katya hello


In [16]:
a = 10 - 2
b = 3.1 - 2.1
println(a, '\n', b)

8
1.0


In [17]:
a = 6/2
b = 5/10
println(a, '\n', b)

3.0
0.5


In [18]:
a = 2^2
b = 3^0.2
println(a, '\n', b)

4
1.2457309396155174


In [19]:
a = sqrt(9)
b = sqrt(25)
println(a, '\n', b)

3.0
5.0


In [20]:
a = 1 < 2
b = 7 > 8
c = 3 == 3
d = 1 != 9
println(a, '\n', b, '\n', c, '\n', d)

true
false
true
true


In [21]:
a = true && false
b = true && true
println(a, '\n', b)

false
true


In [22]:
a = true || false
b = true || true
println(a, '\n', b)

true
true


In [23]:
a = !true
b = !false
println(a, '\n', b)

false
true


In [24]:
A = [1 2; 3 4]
B = [5 6; 7 8]
C = A + B

2×2 Matrix{Int64}:
  6   8
 10  12

In [26]:
A = [1 2; 3 4]
B = [1 1; 2 3]
C = A - B

2×2 Matrix{Int64}:
 0  1
 1  1

In [27]:
A = [1 2; 3 4]
B = [5 6; 7 8]
C = A * B

2×2 Matrix{Int64}:
 19  22
 43  50

In [28]:
A = [1 2; 3 4]
k = 3
C = A * k

2×2 Matrix{Int64}:
 3   6
 9  12

In [29]:
A

2×2 Matrix{Int64}:
 1  2
 3  4

In [30]:
A'

2×2 adjoint(::Matrix{Int64}) with eltype Int64:
 1  3
 2  4

In [31]:
using LinearAlgebra
u = [1, 2, 3]
v = [4, 5, 6]
c = dot(u, v)

32

In [32]:
using LinearAlgebra
u = [1, 2, 3]
v = [4, 5, 6]
c = cross(u, v)

3-element Vector{Int64}:
 -3
  6
 -3